[[dotfiles]]
template = "bin/"
target = "~/bin"

[[dotfiles]]
template = "i3/config"
target = "~/.config/i3/config"

[[dotfiles]]
template = "i3/blocks/"
target = "~/.config/i3/blocks/"

[[dotfiles]]
template = "i3/i3blocks"
target = "~/.i3blocks.conf"

[[dotfiles]]
template = "termite/config"
target = "~/.config/termite/config"

[[dotfiles]]
template = "mpd/"
target = "~/.config/mpd/"

[[dotfiles]]
template = "ncmpcpp/config"
target = "~/.ncmpcpp/config"

[[dotfiles]]
template = "zsh/zshd"
target = "~/.zsh"

[[dotfiles]]
template = "zsh/zprofile"
target = "~/.zprofile"

[[dotfiles]]
template = "zsh/zshrc"
target = "~/.zshrc"

[variables]
font = "Fira Sans"
monofont = "Fira Mono"
# dark0 + gray
color00 = "#282828"
color08 = "#928374"
# neutral_red + bright_red
color01 = "#cc241d"
color09 = "#fb4934"
# neutral_green + bright_green
color02 = "#98971a"
color10 = "#b8bb26"
# neutral_yellow + bright_yellow
color03 = "#d79921"
color11 = "#fabd2f"
# neutral_blue + bright_blue
color04 = "#458588"
color12 = "#83a598"
# neutral_purple + bright_purple
color05 = "#b16286"
color13 = "#d3869b"
# neutral_aqua + faded_aqua
color06 = "#689d6a"
color14 = "#8ec07c"
# light4 + light1
color07 = "#a89984"
color15 = "#ebdbb2"

# vim: set filetype=dosini:
