#!/usr/bin/env bash

statusLine=$(amixer get Master | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $4}' | tr -d '[]')

if [[ "${status}" == "on" ]]; then
  echo "${volume}"
else
  echo "off"
fi
